### PR TITLE
My first commit on variables and keywords

### PR DESCRIPTION
**Pull request by fay-esp96**

### CODE REVIEW

**Review by issa-rajabu-juma — CHANGES_REQUESTED** [review]
Hi faith yourbpull request have been sent against master branch, you are supposed to create your own branch first and the push your codes into it before opening a pull request

**Comment by fay-esp96** [comment]
Got it! Thank you

**Comment by mageta17** [comment]
the script works fine. ila unabidi u redirect the changes to another branch of your own.

**Review by mageta17 — COMMENTED** [review]
the script works fine. ila unabidi u redirect the changes to another branch of your own no sio master branch.

**Comment by Jkarage** [comment]
### In Line 4 of your code,
there is an **"intNum"**  variable,but in the comment you wrote **"num"**

**Pull request closed without merging**
